# -*- coding: utf-8 -*-
"""Base_Score

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTUA-lwPCNzX1Xxvq5mdjpAmk73SKvNI
"""

#Cell 1
import pandas as pd
import numpy as np
import os
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import RandomForestClassifier

#Cell 2
from google.colab import drive
drive.mount('/content/drive')

#Cell 3
file_path = "/content/drive/MyDrive/final_dataset.csv"
df = pd.read_csv(file_path)

print(df.shape)
df.head()

#Cell 4
data_full = df.copy()
data_full["DAYS_EMPLOYED"] = data_full["DAYS_EMPLOYED"].replace(365243, np.nan)

missing_ratio = data_full.isnull().mean()
cols_to_drop = missing_ratio[missing_ratio > 0.5].index
data_full = data_full.drop(columns=cols_to_drop)

print(len(cols_to_drop))
print(data_full.shape)

#Cell 5
upi_features = [
    "total_transactions",
    "avg_transaction_amount",
    "transaction_volatility",
    "weekend_ratio",
    "fraud_ratio",
    "merchant_diversity",
    "device_diversity"
]

existing_upi = [col for col in upi_features if col in data_full.columns]

data_full["stability_index"] = data_full["avg_transaction_amount"] / (data_full["transaction_volatility"] + 1)
data_full["activity_intensity"] = data_full["total_transactions"] / 30
data_full["risk_behavior_score"] = (
    data_full["fraud_ratio"] * 0.5 +
    data_full["transaction_volatility"] * 0.3
)

existing_upi += ["stability_index", "activity_intensity", "risk_behavior_score"]

print(existing_upi)

#Cell 6
y = data_full["TARGET"]
X_full = data_full.drop(columns=["TARGET", "SK_ID_CURR"])

print(X_full.shape)

#Cell 7
cat_cols = X_full.select_dtypes(include="object").columns
X_full = pd.get_dummies(X_full, columns=cat_cols, dummy_na=True)

X_full["income_vs_spend"] = X_full["AMT_INCOME_TOTAL"] / (X_full["avg_transaction_amount"] + 1)
X_full["credit_vs_activity"] = X_full["AMT_CREDIT"] / (X_full["total_transactions"] + 1)

print(X_full.shape)

#Cell 8
X_full = X_full.fillna(X_full.median())

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_full[existing_upi] = scaler.fit_transform(X_full[existing_upi])

print("missing handled + scaling done")

#Cell 9
X_train, X_test, y_train, y_test = train_test_split(
    X_full, y, test_size=0.2, random_state=42
)

print(X_train.shape)
print(X_test.shape)

#Cell 10
X_train_baseline = X_train.drop(columns=existing_upi)
X_test_baseline = X_test.drop(columns=existing_upi)

print(X_train_baseline.shape)

#Cell 11
baseline_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    n_jobs=-1,
    class_weight="balanced",
    random_state=42
)

baseline_model.fit(X_train_baseline, y_train)

print("baseline model trained")

#Cell 12
y_pred_baseline = baseline_model.predict_proba(X_test_baseline)[:,1]

baseline_auc = roc_auc_score(y_test, y_pred_baseline)

print("Baseline ROC-AUC:", baseline_auc)

#Cell 13
X_train_enhanced = X_train.copy()
X_test_enhanced = X_test.copy()

print(X_train_enhanced.shape)

#Cell 14
from xgboost import XGBClassifier

scale_pos_weight = (len(y_train) - sum(y_train)) / sum(y_train)

enhanced_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=scale_pos_weight,
    random_state=42,
    n_jobs=-1
)

enhanced_model.fit(X_train_enhanced, y_train)

print("enhanced model trained")

#Cell 15
y_pred_enhanced = enhanced_model.predict_proba(X_test_enhanced)[:,1]

enhanced_auc = roc_auc_score(y_test, y_pred_enhanced)

print("Enhanced ROC-AUC:", enhanced_auc)

#Cell 16
print("Baseline ROC-AUC:", baseline_auc)
print("Enhanced ROC-AUC:", enhanced_auc)
print("Improvement:", enhanced_auc - baseline_auc)

#Cell 17
pred_df = pd.DataFrame({
    "TARGET": y_test.values,
    "default_probability": y_pred_enhanced
})

pred_df.to_csv("/content/drive/MyDrive/model_predictions.csv", index=False)

print("predictions saved")

#Cell 18
feature_importance = pd.DataFrame({
    "feature": X_train_enhanced.columns,
    "importance": enhanced_model.feature_importances_
}).sort_values(by="importance", ascending=False)

feature_importance.to_csv("/content/drive/MyDrive/feature_importance.csv", index=False)

print("feature importance saved")

#Cell 19
model_path = "/content/drive/MyDrive/enhanced_model.pkl"

if os.path.exists(model_path):
    os.remove(model_path)

joblib.dump(enhanced_model, model_path)

print("model saved")